def print_menu():
    print("\n===== PRODUCT INVENTORY MANAGEMENT =====")
    print("1. Them san pham")
    print("2. Hien thi danh sach san pham")
    print("3. Xem chi tiet san pham theo ma")
    print("4. Cap nhat so luong san pham")
    print("5. Cap nhat gia san pham")
    print("6. Xoa san pham")
    print("7. Tim kiem san pham theo ten")
    print("8. Loc san pham con hang")
    print("9. Sap xep san pham theo gia")
    print("10. Sap xep san pham theo tong gia tri ton kho")
    print("11. Tim san pham co gia cao nhat")
    print("12. Tinh thong ke kho hang")
    print("13. Luu du lieu ra file JSON")
    print("14. Doc du lieu tu file JSON")
    print("0. Thoat chuong trinh")
